export const SET_UTILS = "SET_UTILS";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SCROLL = "SET_SCROLL";
export const SET_STUDIO = "SET_STUDIO";