version: '3.5'

services:
  andumy-backend:
    build:
      context: './docker/apache'
      args:
        uid: ${UID}
    container_name: andumy-backend
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - ${HOST_PORT}:80
    networks:
      andumy-backend-network:
        aliases:
          - andumy-backend

  andumy-db:
    image: mysql:5.7
    container_name: andumy-db
    volumes:
      - ./docker/mysql/run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      andumy-backend-network:
        aliases:
          - andumy-db
  
  andumy-pma:
    depends_on: 
      - andumy-db
    image: phpmyadmin/phpmyadmin
    container_name: andumy-pma
    volumes:
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
    ports:
      - '9001:80'
    environment:
      PMA_HOST: andumy-db
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
    networks:
      andumy-backend-network:
        aliases:
          - andumy-pma

networks:
  andumy-backend-network:
    name: andumy-backend-network