version: '3.5'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: andumy-front
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
      - ${HOST_PORT}:3000
    networks:
      andumy-backend-network:
        aliases:
          - react-app
    stdin_open: true
    
networks:
  andumy-backend-network:
    name: andumy-backend